# Generated by Django 3.2.10 on 2022-05-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0002_location_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
    ]
