# Generated by Django 3.2.10 on 2022-05-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0003_auto_20220506_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loc_img', to='places_to_go.location', verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
