# Generated by Django 3.2.10 on 2022-05-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0004_locationimage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='position',
            field=models.SmallIntegerField(default=1, unique=True, verbose_name='Позиция'),
            preserve_default=False,
        ),
    ]
