# Generated by Django 3.1.14 on 2022-05-16 13:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0007_auto_20220516_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='long_describtion',
            field=tinymce.models.HTMLField(),
        ),
    ]
