# Generated by Django 3.1.14 on 2022-05-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0009_auto_20220525_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places_to_go.location', verbose_name='Локация'),
        ),
    ]
